#ifndef TEST_H
#define TEST_H
#include "Encoder.h"
void testEncoder(uint8_t);
void testVlx(uint8_t);
void testVlxFrontLeft();
void testVlxFrontRigth();
void testVlxRight();
void testVlxLeft();
void testVlxBackLeft();
void testVlxFront();
void testVlxrightDown();
void testVlxRightUp();
void testMotors();
void testTCS();
void testEncoders();
void testPIDWheel();
void testButton();
void testVlxFrontDistance();
void testBnoY();
void calibrateColors();
void testLimits();
void pidTest();
#endif